[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gcd = "2.3.0"
dotenvy = "0.15.7"
indoc = "2.0.4"
itertools = "0.12.0"
pollster = "0.3.0"
ureq = "2.9.1"
